baseURL = 'https://blog.sihle.cc/'
languageCode = 'zh-Hant-TW'
title = 'Matsuzu'
theme = 'ananke'

# DefaultContentLanguage = "zh-hant"
enableRobotsTXT = true
SectionPagesMenu = "main"

[params]
  favicon = ""
  site_logo = ""
  author = "SIHLE HUANG"
  description = "SIHLE 的個人部落格"
  show_reading_time = true
  read_more_copy = "閱讀更多"
  body_classes = "noto-sans-tc bg-near-white"
  custom_css = ["custom.css"]
  text_color = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/GoHugoIO"

[services]
  [services.googleAnalytics]
    id = 'G-TGSPYX8ZYZ'
  [services.disqus]
    shortname = 'matsuzu'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
